### ISSUE TITLE
leaderboard command shows "mode2"

### ISSUE THREAD

**Issue by FEZfan** [monkeytypegame/monkeytype-bot#84]
![Screen Shot 2022-06-11 at 13 59 38](https://user-images.githubusercontent.com/47842376/173171727-b6e6b060-b97d-4d91-b3ef-80f67d57e97c.png)

**Comment by Ferotiq** [comment]
I guess it's a little bit undocumented but basically that's just `15` or `60`, being the modes that we currently have for the leaderboard.
